version: "3.4"
services:
  bitcoinwalletnode.dnp.dappnode.eth:
    image: "bitcoinwalletnode.dnp.dappnode.eth:0.2.0"
    build: ./build
    volumes:
      - "bitcoin_data:/root/.bitcoin"
    ports:
      - "8333:8333"
    environment:
      - BTC_RPCUSER=dappnode
      - BTC_RPCPASSWORD=dappnode
      - BTC_TXINDEX=1
      - BTC_PRUNE=0
      - BTC_DISABLEWALLET=1
    restart: always
volumes:
  bitcoin_data: {}
