version: '3.4'
services:
  bitcoin.dnp.dappnode.eth:
    image: 'bitcoin.dnp.dappnode.eth:0.1.6'
    build: ./build
    volumes:
      - 'bitcoin_data:/root/.bitcoin'
    ports:
      - '8333:8333'
    environment:
      - BTC_RPCUSER=dappnode
      - BTC_RPCPASSWORD=dappnode
      - BTC_TXINDEX=1
      - BTC_PRUNE=0
      - BTC_DISABLEWALLET=1
    restart: always
volumes:
  bitcoin_data: {}
